#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

$application = new \Aurora\Framework\Core\Application([
    \Aurora\Modules\HomePage\HomePageModule::class,
    \Aurora\Modules\Auth\AuthModule::class,
]);

$application->runConsole();